apiVersion: v1
kind: Service
metadata:
  name: dev-nginx-service   # correspond au namePrefix + nom dans base
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30083   # NodePort souhaité pour cet overlay
